name: Node CI

on: push
permissions:
  contents: read
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 18.x
      uses: actions/setup-node@v1
      with:
        node-version: 18.x
    - name: npm install, build, and test
      run: |
        npm install
        npm test
      env:
        CI: true
